--
-- DRIMS Complete Database Schema
-- Disaster Relief Inventory Management System
-- Government of Jamaica - ODPEM
--
-- This schema combines:
-- 1. aidmgmt-3.sql (original ODPEM disaster relief schema)
-- 2. DRIMS extensions (user management, notifications, enhanced workflows)
--
-- Database: PostgreSQL 12+
-- Required Extensions: citext
--

--
-- Extensions
--
CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================================================
-- SECTION 1: REFERENCE TABLES (from aidmgmt-3.sql)
-- ============================================================================

--
-- Country table
--
CREATE TABLE country (
    country_id SMALLINT NOT NULL PRIMARY KEY,
    country_name VARCHAR(80) NOT NULL
);

--
-- Parish table (Jamaican parishes)
--
CREATE TABLE parish (
    parish_code CHAR(2) NOT NULL PRIMARY KEY
        CHECK (parish_code SIMILAR TO '[0-9]*' AND parish_code::INTEGER BETWEEN 1 AND 14),
    parish_name VARCHAR(40) NOT NULL
);

--
-- Unit of Measure table
--
CREATE TABLE unitofmeasure (
    uom_code VARCHAR(25) NOT NULL PRIMARY KEY
        CHECK (uom_code = UPPER(uom_code)),
    uom_desc VARCHAR(60) NOT NULL,
    comments_text TEXT,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

--
-- Item Category table
--
CREATE TABLE itemcatg (
    category_code VARCHAR(30) NOT NULL PRIMARY KEY
        CHECK (category_code = UPPER(category_code)),
    category_desc VARCHAR(60) NOT NULL,
    comments_text TEXT,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

-- ============================================================================
-- SECTION 2: CORE ENTITY TABLES (from aidmgmt-3.sql)
-- ============================================================================

--
-- Event table - Disaster events
--
CREATE TABLE event (
    event_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(16) NOT NULL
        CHECK (event_type IN ('STORM','TORNADO','FLOOD','TSUNAMI','FIRE','EARTHQUAKE','WAR','EPIDEMIC')),
    start_date DATE NOT NULL
        CHECK (start_date <= CURRENT_DATE),
    event_name VARCHAR(60) NOT NULL,
    event_desc VARCHAR(255) NOT NULL,
    impact_desc TEXT NOT NULL,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('A','C')),  -- A=Active, C=Closed
    closed_date DATE
        CHECK ((status_code = 'A' AND closed_date IS NULL) 
            OR (status_code = 'C' AND closed_date IS NOT NULL)),
    reason_desc VARCHAR(255)
        CHECK ((reason_desc IS NULL AND closed_date IS NULL)
            OR (reason_desc IS NOT NULL AND closed_date IS NOT NULL)),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

--
-- Donor table
--
CREATE TABLE donor (
    donor_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_type CHAR(1) NOT NULL
        CHECK (donor_type IN ('I','O')),  -- I=Individual, O=Organization
    donor_name VARCHAR(255) NOT NULL
        CHECK (donor_name = UPPER(donor_name)),
    org_type_desc VARCHAR(30),
    address1_text VARCHAR(255) NOT NULL,
    address2_text VARCHAR(255),
    country_id SMALLINT NOT NULL DEFAULT 388 REFERENCES country,
    phone_no VARCHAR(20) NOT NULL,
    email_text VARCHAR(100),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    CONSTRAINT uk_donor_1 UNIQUE (donor_name)
);

--
-- Custodian table - GOJ agency (ODPEM)
--
CREATE TABLE custodian (
    custodian_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custodian_name VARCHAR(120) NOT NULL 
        DEFAULT 'OFFICE OF DISASTER PREPAREDNESS AND EMERGENCY MANAGEMENT (ODPEM)'
        CHECK (custodian_name = UPPER(custodian_name)),
    address1_text VARCHAR(255) NOT NULL,
    address2_text VARCHAR(255),
    parish_code CHAR(2) NOT NULL REFERENCES parish,
    contact_name VARCHAR(50) NOT NULL
        CHECK (contact_name = UPPER(contact_name)),
    phone_no VARCHAR(20) NOT NULL,
    email_text VARCHAR(100),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    CONSTRAINT uk_custodian_1 UNIQUE (custodian_name)
);

--
-- Item table - Relief items
--
CREATE TABLE item (
    item_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(60) NOT NULL
        CHECK (item_name = UPPER(item_name)),
    sku_code VARCHAR(30) NOT NULL
        CHECK (sku_code = UPPER(sku_code)),
    category_code VARCHAR(30) NOT NULL REFERENCES itemcatg,
    item_desc CITEXT NOT NULL,
    reorder_qty DECIMAL(12,2) NOT NULL
        CHECK (reorder_qty > 0.00),
    default_uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    usage_desc TEXT,
    storage_desc TEXT,
    expiration_apply_flag BOOLEAN NOT NULL,
    comments_text TEXT,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('A','I')),  -- A=Active, I=Inactive
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    CONSTRAINT uk_item_1 UNIQUE (item_name),
    CONSTRAINT uk_item_2 UNIQUE (sku_code)
);
CREATE INDEX dk_item_1 ON item(item_desc);

--
-- Warehouse table - Storage locations
--
CREATE TABLE warehouse (
    warehouse_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name TEXT NOT NULL,
    warehouse_type VARCHAR(10) NOT NULL
        CHECK (warehouse_type IN ('MAIN','HUB','SUB-HUB','AGENCY')),
    address1_text VARCHAR(255) NOT NULL,
    address2_text VARCHAR(255),
    parish_code CHAR(2) NOT NULL REFERENCES parish,
    contact_name VARCHAR(50) NOT NULL
        CHECK (contact_name = UPPER(contact_name)),
    phone_no VARCHAR(20) NOT NULL,
    email_text VARCHAR(100),
    custodian_id INTEGER NOT NULL REFERENCES custodian,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('A','I')),  -- A=Active, I=Inactive
    reason_desc VARCHAR(255)
        CHECK ((reason_desc IS NULL AND status_code = 'A')
            OR (reason_desc IS NOT NULL AND status_code = 'I')),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

--
-- Agency table - Request-only locations
--
CREATE TABLE agency (
    agency_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_name VARCHAR(120) NOT NULL
        CHECK (agency_name = UPPER(agency_name)),
    address1_text VARCHAR(255) NOT NULL,
    address2_text VARCHAR(255),
    parish_code CHAR(2) NOT NULL REFERENCES parish,
    contact_name VARCHAR(50) NOT NULL
        CHECK (contact_name = UPPER(contact_name)),
    phone_no VARCHAR(20) NOT NULL,
    email_text VARCHAR(100),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    CONSTRAINT uk_agency_1 UNIQUE (agency_name)
);

-- ============================================================================
-- SECTION 3: INVENTORY MANAGEMENT (from aidmgmt-3.sql)
-- ============================================================================

--
-- Inventory table - Stock levels by warehouse and item
--
CREATE TABLE inventory (
    inventory_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse,
    item_id INTEGER NOT NULL REFERENCES item,
    usable_qty DECIMAL(12,2) NOT NULL CHECK (usable_qty >= 0.00),
    reserved_qty DECIMAL(12,2) NOT NULL CHECK (reserved_qty <= usable_qty),
    defective_qty DECIMAL(12,2) NOT NULL CHECK (defective_qty >= 0.00),
    expired_qty DECIMAL(12,2) NOT NULL CHECK (expired_qty >= 0.00),
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    last_verified_by VARCHAR(20),
    last_verified_date DATE
        CHECK ((last_verified_by IS NULL AND last_verified_date IS NULL)
            OR (last_verified_by IS NOT NULL AND last_verified_date IS NOT NULL)),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('A','U')),  -- A=Available, U=Unavailable
    comments_text TEXT,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);
CREATE UNIQUE INDEX uk_inventory_1 ON inventory(item_id, inventory_id);
CREATE INDEX dk_inventory_1 ON inventory(warehouse_id);
CREATE UNIQUE INDEX uk_inventory_2 ON inventory(item_id) WHERE usable_qty > 0.00;

--
-- Location table - Physical storage locations within warehouses
--
CREATE TABLE location (
    location_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id INTEGER NOT NULL REFERENCES inventory,
    location_desc VARCHAR(255) NOT NULL,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('O','C')),  -- O=Open, C=Closed
    comments_text VARCHAR(255),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);
CREATE INDEX dk_location_1 ON location(inventory_id);

--
-- Item Location table - Items at specific locations
--
CREATE TABLE item_location (
    inventory_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    location_id INTEGER NOT NULL REFERENCES location,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (item_id, inventory_id) REFERENCES inventory(item_id, inventory_id),
    PRIMARY KEY (item_id, location_id)
);
CREATE INDEX dk_item_location_1 ON item_location(inventory_id, location_id);

-- ============================================================================
-- SECTION 4: DONATION MANAGEMENT (from aidmgmt-3.sql)
-- ============================================================================

--
-- Donation table
--
CREATE TABLE donation (
    donation_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id INTEGER NOT NULL REFERENCES donor,
    donation_desc TEXT NOT NULL,
    event_id INTEGER NOT NULL REFERENCES event,
    custodian_id INTEGER NOT NULL REFERENCES custodian,
    received_date DATE NOT NULL CHECK (received_date <= CURRENT_DATE),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('E','V')),  -- E=Entered, V=Verified
    comments_text TEXT,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);

--
-- Donation Item table
--
CREATE TABLE donation_item (
    donation_id INTEGER NOT NULL REFERENCES donation,
    item_id INTEGER NOT NULL REFERENCES item,
    item_qty DECIMAL(12,2) NOT NULL CHECK (item_qty >= 0.00),
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    location_name TEXT NOT NULL,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('P','V')),  -- P=Pending verification, V=Verified
    comments_text TEXT,
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    PRIMARY KEY (donation_id, item_id)
);

--
-- Donation Intake table
--
CREATE TABLE dnintake (
    donation_id INTEGER NOT NULL REFERENCES donation,
    inventory_id INTEGER NOT NULL REFERENCES inventory,
    intake_date DATE NOT NULL CHECK (intake_date <= CURRENT_DATE),
    comments_text VARCHAR(255),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('I','C','V')),  -- I=Incomplete, C=Completed, V=Verified
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    PRIMARY KEY (donation_id, inventory_id)
);

--
-- Donation Intake Item table
--
CREATE TABLE dnintake_item (
    donation_id INTEGER NOT NULL,
    inventory_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    usable_qty DECIMAL(12,2) NOT NULL CHECK (usable_qty >= 0.00),
    location1_id INTEGER REFERENCES location,
    defective_qty DECIMAL(12,2) NOT NULL CHECK (defective_qty >= 0.00),
    location2_id INTEGER REFERENCES location,
    expired_qty DECIMAL(12,2) NOT NULL CHECK (expired_qty >= 0.00),
    location3_id INTEGER REFERENCES location,
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('P','V')),  -- P=Pending verification, V=Verified
    comments_text VARCHAR(255),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    FOREIGN KEY (donation_id, inventory_id) REFERENCES dnintake(donation_id, inventory_id),
    PRIMARY KEY (donation_id, inventory_id, item_id)
);
CREATE INDEX dk_dnintake_item_1 ON dnintake_item(inventory_id, item_id);
CREATE INDEX dk_dnintake_item_2 ON dnintake_item(item_id);

-- ============================================================================
-- SECTION 5: TRANSFER MANAGEMENT (from aidmgmt-3.sql)
-- ============================================================================

--
-- Transfer table
--
CREATE TABLE transfer (
    transfer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fr_inventory_id INTEGER NOT NULL REFERENCES inventory,
    to_inventory_id INTEGER NOT NULL REFERENCES inventory,
    transfer_date DATE NOT NULL CHECK (transfer_date <= CURRENT_DATE),
    transport_mode VARCHAR(255),
    comments_text VARCHAR(255),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('P','C','V','D')),  
        -- P=Processing, C=Completed, V=Verified, D=Dispatched
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL
);
CREATE INDEX dk_transfer_1 ON transfer(transfer_date);
CREATE INDEX dk_transfer_2 ON transfer(fr_inventory_id);
CREATE INDEX dk_transfer_3 ON transfer(to_inventory_id);

--
-- Transfer Item table
--
CREATE TABLE transfer_item (
    transfer_id INTEGER NOT NULL REFERENCES transfer,
    item_id INTEGER NOT NULL,
    item_qty DECIMAL(12,2) NOT NULL CHECK (item_qty >= 0.00),
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    reason_text VARCHAR(255),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    PRIMARY KEY (transfer_id, item_id)
);
CREATE INDEX dk_transfer_item_1 ON transfer_item(item_id);

-- ============================================================================
-- SECTION 6: RELIEF REQUEST MANAGEMENT (from aidmgmt-3.sql)
-- ============================================================================

--
-- Relief Request table (Needs Lists)
--
CREATE TABLE reliefrqst (
    reliefrqst_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id INTEGER NOT NULL REFERENCES agency,
    request_date DATE NOT NULL CHECK (request_date <= CURRENT_DATE),
    urgency_ind CHAR(1) NOT NULL
        CHECK (urgency_ind IN ('L','M','H','C')),  -- L=Low, M=Medium, H=High, C=Critical
    status_code SMALLINT NOT NULL
        CHECK (status_code BETWEEN 0 AND 7),
        -- 0=Draft, 1=Awaiting approval, 2=Cancelled, 3=Submitted,
        -- 4=Denied, 5=Part filled, 6=Closed, 7=Filled
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    review_by_id VARCHAR(20)
        CHECK ((review_by_id IS NULL AND status_code < 2)
            OR (review_by_id IS NOT NULL AND status_code >= 2)),
    review_dtime TIMESTAMP(0) WITHOUT TIME ZONE
        CHECK ((review_by_id IS NULL AND review_dtime IS NULL)
            OR (review_by_id IS NOT NULL AND review_dtime IS NOT NULL)),
    action_by_id VARCHAR(20)
        CHECK ((action_by_id IS NULL AND status_code < 4)
            OR (action_by_id IS NOT NULL AND status_code >= 4)),
    action_dtime TIMESTAMP(0) WITHOUT TIME ZONE
        CHECK ((action_by_id IS NULL AND action_dtime IS NULL)
            OR (action_by_id IS NOT NULL AND action_dtime IS NOT NULL)),
    version_nbr INTEGER NOT NULL
);
CREATE INDEX dk_reliefrqst_1 ON reliefrqst(agency_id, request_date);
CREATE INDEX dk_reliefrqst_2 ON reliefrqst(request_date, status_code);
CREATE INDEX dk_reliefrqst_3 ON reliefrqst(status_code, urgency_ind);

--
-- Relief Request Item table
--
CREATE TABLE reliefrqst_item (
    reliefrqst_id INTEGER NOT NULL REFERENCES reliefrqst,
    item_id INTEGER NOT NULL REFERENCES item,
    request_qty DECIMAL(12,2) NOT NULL CHECK (request_qty > 0.00),
    issue_qty DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (issue_qty <= request_qty),
    urgency_ind CHAR(1) NOT NULL
        CHECK (urgency_ind IN ('L','M','H','C')),
    rqst_reason_desc VARCHAR(255)
        CHECK ((rqst_reason_desc IS NOT NULL)
            OR (rqst_reason_desc IS NULL AND urgency_ind IN ('L','M'))),
    required_by_date DATE
        CHECK ((required_by_date IS NOT NULL)
            OR (required_by_date IS NULL AND urgency_ind IN ('L','M'))),
    status_code CHAR(1) NOT NULL DEFAULT 'R'
        CHECK (status_code IN ('R','U','W','D','P','L','F')),
        -- R=Requested, U=Unavailable, W=Waiting availability,
        -- D=Denied, P=Partly filled, L=Limit allowed, F=Filled
    status_reason_desc VARCHAR(255),
    action_by_id VARCHAR(20)
        CHECK ((action_by_id IS NULL AND status_code = 'R') 
            OR (action_by_id IS NOT NULL AND status_code != 'R')),
    action_dtime TIMESTAMP(0) WITHOUT TIME ZONE
        CHECK ((action_by_id IS NULL AND action_dtime IS NULL) 
            OR (action_by_id IS NOT NULL AND action_dtime IS NOT NULL)),
    version_nbr INTEGER NOT NULL,
    PRIMARY KEY (reliefrqst_id, item_id)
);

--
-- Relief Package table (Fulfilments)
--
CREATE TABLE reliefpkg (
    reliefpkg_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_inventory_id INTEGER NOT NULL REFERENCES inventory,
    reliefrqst_id INTEGER NOT NULL REFERENCES reliefrqst,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE CHECK (start_date <= CURRENT_DATE),
    dispatch_dtime TIMESTAMP(0) WITHOUT TIME ZONE
        CHECK ((dispatch_dtime IS NULL AND status_code != 'D')
            OR (dispatch_dtime IS NOT NULL AND status_code = 'D')),
    transport_mode VARCHAR(255),
    comments_text VARCHAR(255),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('P','C','V','D')),
        -- P=Processing, C=Completed, V=Verified, D=Dispatched
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    version_nbr INTEGER NOT NULL
);
CREATE INDEX dk_reliefpkg_1 ON reliefpkg(start_date);
CREATE INDEX dk_reliefpkg_3 ON reliefpkg(to_inventory_id);

--
-- Relief Package Item table
--
CREATE TABLE reliefpkg_item (
    reliefpkg_id INTEGER NOT NULL REFERENCES reliefpkg,
    fr_inventory_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    item_qty DECIMAL(12,2) NOT NULL CHECK (item_qty >= 0.00),
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    reason_text VARCHAR(255),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    FOREIGN KEY (item_id, fr_inventory_id) REFERENCES inventory(item_id, inventory_id),
    PRIMARY KEY (reliefpkg_id, fr_inventory_id, item_id)
);
CREATE INDEX dk_reliefpkg_item_1 ON reliefpkg_item(fr_inventory_id, item_id);
CREATE INDEX dk_reliefpkg_item_2 ON reliefpkg_item(item_id);

--
-- Distribution Intake table (Receipt at destination)
--
CREATE TABLE dbintake (
    reliefpkg_id INTEGER NOT NULL REFERENCES reliefpkg,
    inventory_id INTEGER NOT NULL REFERENCES inventory,
    intake_date DATE NOT NULL CHECK (intake_date <= CURRENT_DATE),
    comments_text VARCHAR(255),
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('I','C','V')),  -- I=Incomplete, C=Completed, V=Verified
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    verify_by_id VARCHAR(20) NOT NULL,
    verify_dtime TIMESTAMP(0) WITHOUT TIME ZONE,
    version_nbr INTEGER NOT NULL,
    PRIMARY KEY (reliefpkg_id, inventory_id)
);

--
-- Distribution Intake Item table
--
CREATE TABLE dbintake_item (
    reliefpkg_id INTEGER NOT NULL,
    inventory_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    usable_qty DECIMAL(12,2) NOT NULL CHECK (usable_qty >= 0.00),
    location1_id INTEGER REFERENCES location,
    defective_qty DECIMAL(12,2) NOT NULL CHECK (defective_qty >= 0.00),
    location2_id INTEGER REFERENCES location,
    expired_qty DECIMAL(12,2) NOT NULL CHECK (expired_qty >= 0.00),
    location3_id INTEGER REFERENCES location,
    uom_code VARCHAR(25) NOT NULL REFERENCES unitofmeasure,
    status_code CHAR(1) NOT NULL
        CHECK (status_code IN ('P','V')),  -- P=Pending verification, V=Verified
    comments_text VARCHAR(255),
    create_by_id VARCHAR(20) NOT NULL,
    create_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    update_by_id VARCHAR(20) NOT NULL,
    update_dtime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    version_nbr INTEGER NOT NULL,
    FOREIGN KEY (reliefpkg_id, inventory_id) REFERENCES dbintake(reliefpkg_id, inventory_id),
    PRIMARY KEY (reliefpkg_id, inventory_id, item_id)
);
CREATE INDEX dk_dbintake_item_1 ON dbintake_item(inventory_id, item_id);
CREATE INDEX dk_dbintake_item_2 ON dbintake_item(item_id);

-- ============================================================================
-- SECTION 7: DRIMS EXTENSION TABLES
-- ============================================================================

--
-- DRIMS Needs List table (Enhanced modern workflow)
--
CREATE TABLE needs_list (
    id SERIAL PRIMARY KEY,
    list_number VARCHAR(64) UNIQUE NOT NULL,
    agency_id INTEGER NOT NULL REFERENCES agency(agency_id),
    event_id INTEGER NOT NULL REFERENCES event(event_id),
    submission_type VARCHAR(20) DEFAULT 'DRAFT' NOT NULL,
    requested_by_name VARCHAR(200),
    requested_by_contact VARCHAR(200),
    priority VARCHAR(20) DEFAULT 'MEDIUM' NOT NULL,
    urgency VARCHAR(20) DEFAULT 'ROUTINE',
    status VARCHAR(50) DEFAULT 'Draft' NOT NULL,
    is_draft BOOLEAN DEFAULT TRUE NOT NULL,
    is_locked BOOLEAN DEFAULT FALSE NOT NULL,
    locked_by VARCHAR(200),
    locked_at TIMESTAMP,
    notes TEXT,
    justification TEXT,
    review_notes TEXT,
    created_by VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP,
    reviewed_by VARCHAR(200),
    reviewed_at TIMESTAMP,
    approved_by VARCHAR(200),
    approved_at TIMESTAMP
);
CREATE INDEX idx_needs_list_agency ON needs_list(agency_id);
CREATE INDEX idx_needs_list_status ON needs_list(status);
CREATE INDEX idx_needs_list_number ON needs_list(list_number);
CREATE INDEX idx_needs_list_event ON needs_list(event_id);

--
-- DRIMS Needs List Item table
--
CREATE TABLE needs_list_item (
    id SERIAL PRIMARY KEY,
    needs_list_id INTEGER NOT NULL REFERENCES needs_list(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES item(item_id),
    requested_qty DECIMAL(12,2) NOT NULL,
    approved_qty DECIMAL(12,2) DEFAULT 0 NOT NULL,
    fulfilled_qty DECIMAL(12,2) DEFAULT 0 NOT NULL,
    notes TEXT,
    justification TEXT,
    status VARCHAR(50) DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_needs_list_item_list ON needs_list_item(needs_list_id);
CREATE INDEX idx_needs_list_item_item ON needs_list_item(item_id);

--
-- DRIMS Fulfilment table
--
CREATE TABLE fulfilment (
    id SERIAL PRIMARY KEY,
    needs_list_id INTEGER NOT NULL REFERENCES needs_list(id),
    fulfilment_number VARCHAR(64) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'In Preparation' NOT NULL,
    is_partial BOOLEAN DEFAULT FALSE NOT NULL,
    notes TEXT,
    prepared_by VARCHAR(200),
    prepared_at TIMESTAMP,
    dispatched_by VARCHAR(200),
    dispatched_at TIMESTAMP,
    received_by VARCHAR(200),
    received_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_fulfilment_needs_list ON fulfilment(needs_list_id);
CREATE INDEX idx_fulfilment_number ON fulfilment(fulfilment_number);
CREATE INDEX idx_fulfilment_status ON fulfilment(status);

--
-- DRIMS Fulfilment Line Item table
--
CREATE TABLE fulfilment_line_item (
    id SERIAL PRIMARY KEY,
    fulfilment_id INTEGER NOT NULL REFERENCES fulfilment(id) ON DELETE CASCADE,
    source_warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    item_id INTEGER NOT NULL REFERENCES item(item_id),
    allocated_qty DECIMAL(12,2) NOT NULL,
    dispatched_qty DECIMAL(12,2) DEFAULT 0 NOT NULL,
    received_qty DECIMAL(12,2) DEFAULT 0 NOT NULL,
    notes TEXT,
    status VARCHAR(50) DEFAULT 'Allocated',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_fulfilment_line_item_fulfilment ON fulfilment_line_item(fulfilment_id);
CREATE INDEX idx_fulfilment_line_item_warehouse ON fulfilment_line_item(source_warehouse_id);
CREATE INDEX idx_fulfilment_line_item_item ON fulfilment_line_item(item_id);

--
-- DRIMS Fulfilment Edit Log table
--
CREATE TABLE fulfilment_edit_log (
    id SERIAL PRIMARY KEY,
    fulfilment_id INTEGER NOT NULL REFERENCES fulfilment(id),
    line_item_id INTEGER REFERENCES fulfilment_line_item(id),
    field_changed VARCHAR(100) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    reason TEXT,
    changed_by VARCHAR(200) NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_fulfilment_edit_log_fulfilment ON fulfilment_edit_log(fulfilment_id);

--
-- DRIMS Dispatch Manifest table
--
CREATE TABLE dispatch_manifest (
    id SERIAL PRIMARY KEY,
    fulfilment_id INTEGER NOT NULL REFERENCES fulfilment(id),
    manifest_number VARCHAR(64) UNIQUE NOT NULL,
    from_warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    to_warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    vehicle_info VARCHAR(200),
    driver_name VARCHAR(200),
    driver_contact VARCHAR(100),
    dispatch_notes TEXT,
    dispatched_by VARCHAR(200) NOT NULL,
    dispatched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_dispatch_manifest_fulfilment ON dispatch_manifest(fulfilment_id);
CREATE INDEX idx_dispatch_manifest_from ON dispatch_manifest(from_warehouse_id);
CREATE INDEX idx_dispatch_manifest_to ON dispatch_manifest(to_warehouse_id);

--
-- DRIMS Receipt Record table
--
CREATE TABLE receipt_record (
    id SERIAL PRIMARY KEY,
    fulfilment_id INTEGER NOT NULL REFERENCES fulfilment(id),
    receipt_number VARCHAR(64) UNIQUE NOT NULL,
    received_by VARCHAR(200) NOT NULL,
    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    condition_notes TEXT,
    discrepancy_notes TEXT,
    signature_path VARCHAR(500)
);
CREATE INDEX idx_receipt_record_fulfilment ON receipt_record(fulfilment_id);

--
-- DRIMS Distribution Package table (Alternative workflow)
--
CREATE TABLE distribution_package (
    id SERIAL PRIMARY KEY,
    package_number VARCHAR(64) UNIQUE NOT NULL,
    recipient_agency_id INTEGER NOT NULL REFERENCES agency(agency_id),
    assigned_warehouse_id INTEGER REFERENCES warehouse(warehouse_id),
    event_id INTEGER REFERENCES event(event_id),
    status VARCHAR(50) DEFAULT 'Draft' NOT NULL,
    is_partial BOOLEAN DEFAULT FALSE NOT NULL,
    created_by VARCHAR(200) NOT NULL,
    approved_by VARCHAR(200),
    approved_at TIMESTAMP,
    dispatched_by VARCHAR(200),
    dispatched_at TIMESTAMP,
    delivered_at TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_distribution_package_agency ON distribution_package(recipient_agency_id);
CREATE INDEX idx_distribution_package_warehouse ON distribution_package(assigned_warehouse_id);
CREATE INDEX idx_distribution_package_event ON distribution_package(event_id);

--
-- DRIMS Distribution Package Item table
--
CREATE TABLE distribution_package_item (
    id SERIAL PRIMARY KEY,
    package_id INTEGER NOT NULL REFERENCES distribution_package(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES item(item_id),
    quantity DECIMAL(12,2) NOT NULL,
    notes TEXT
);
CREATE INDEX idx_distribution_package_item_package ON distribution_package_item(package_id);
CREATE INDEX idx_distribution_package_item_item ON distribution_package_item(item_id);

--
-- User table (DRIMS authentication)
--
CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    full_name VARCHAR(200),
    role VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    organization VARCHAR(200),
    job_title VARCHAR(200),
    phone VARCHAR(50),
    timezone VARCHAR(50) DEFAULT 'America/Jamaica' NOT NULL,
    language VARCHAR(10) DEFAULT 'en' NOT NULL,
    notification_preferences TEXT,
    assigned_warehouse_id INTEGER REFERENCES warehouse(warehouse_id),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by_id INTEGER REFERENCES "user"(id),
    updated_by_id INTEGER REFERENCES "user"(id)
);
CREATE INDEX idx_user_email ON "user"(email);

--
-- Role table (DRIMS role definitions)
--
CREATE TABLE role (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_role_code ON role(code);

--
-- User Role table (many-to-many)
--
CREATE TABLE user_role (
    user_id INTEGER NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES role(id) ON DELETE CASCADE,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by INTEGER REFERENCES "user"(id),
    PRIMARY KEY (user_id, role_id)
);

--
-- User Warehouse table (warehouse access control)
--
CREATE TABLE user_warehouse (
    user_id INTEGER NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id) ON DELETE CASCADE,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    assigned_by INTEGER REFERENCES "user"(id),
    PRIMARY KEY (user_id, warehouse_id)
);

--
-- Notification table (in-app notifications)
--
CREATE TABLE notification (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    warehouse_id INTEGER REFERENCES warehouse(warehouse_id),
    reliefrqst_id INTEGER REFERENCES reliefrqst(reliefrqst_id),
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'unread' NOT NULL,
    link_url VARCHAR(500),
    payload TEXT,
    is_archived BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX idx_notification_user_status ON notification(user_id, status, created_at);
CREATE INDEX idx_notification_warehouse ON notification(warehouse_id, created_at);

--
-- Transfer Request table (enhanced transfer workflow - DRIMS extension)
--
CREATE TABLE transfer_request (
    id SERIAL PRIMARY KEY,
    from_warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    to_warehouse_id INTEGER NOT NULL REFERENCES warehouse(warehouse_id),
    item_id INTEGER NOT NULL REFERENCES item(item_id),
    quantity DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    requested_by INTEGER REFERENCES "user"(id),
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_by INTEGER REFERENCES "user"(id),
    reviewed_at TIMESTAMP,
    notes TEXT
);

--
-- Transaction table (legacy compatibility - DRIMS)
--
CREATE TABLE transaction (
    id SERIAL PRIMARY KEY,
    item_id INTEGER REFERENCES item(item_id),
    ttype VARCHAR(8) NOT NULL,
    qty DECIMAL(12,2) NOT NULL,
    warehouse_id INTEGER REFERENCES warehouse(warehouse_id),
    donor_id INTEGER REFERENCES donor(donor_id),
    event_id INTEGER REFERENCES event(event_id),
    expiry_date DATE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(200)
);

-- ============================================================================
-- SECTION 8: SEED DATA
-- ============================================================================

-- Jamaica Parishes
INSERT INTO parish (parish_code, parish_name) VALUES
('01', 'Kingston'), ('02', 'St. Andrew'), ('03', 'St. Thomas'),
('04', 'Portland'), ('05', 'St. Mary'), ('06', 'St. Ann'),
('07', 'Trelawny'), ('08', 'St. James'), ('09', 'Hanover'),
('10', 'Westmoreland'), ('11', 'St. Elizabeth'), ('12', 'Manchester'),
('13', 'Clarendon'), ('14', 'St. Catherine');

-- Unit of Measure
INSERT INTO unitofmeasure (uom_code, uom_desc, create_by_id, create_dtime, update_by_id, update_dtime, version_nbr) VALUES
('UNIT', 'Individual units', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('KG', 'Kilograms', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('LITRE', 'Litres', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('BOX', 'Boxes', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('SACK', 'Sacks', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('BOTTLE', 'Bottles', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('GALLON', 'Gallons', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('METRE', 'Metres', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('SHEET', 'Sheets', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1);

-- Item Categories
INSERT INTO itemcatg (category_code, category_desc, create_by_id, create_dtime, update_by_id, update_dtime, version_nbr) VALUES
('FOOD', 'Food Items', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('WATER', 'Water and Beverages', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('HYGIENE', 'Hygiene Products', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('MEDICAL', 'Medical Supplies', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('SHELTER', 'Shelter Materials', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('CLOTHING', 'Clothing and Bedding', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('CONSTRUCTION', 'Construction Materials', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('TOOLS', 'Tools and Equipment', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1),
('OTHER', 'Other Items', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1);

-- Custodian (ODPEM)
INSERT INTO custodian (custodian_name, address1_text, parish_code, contact_name, phone_no, email_text, 
    create_by_id, create_dtime, update_by_id, update_dtime, version_nbr) VALUES
('OFFICE OF DISASTER PREPAREDNESS AND EMERGENCY MANAGEMENT (ODPEM)', 
 '2 Haining Road', '01', 'DIRECTOR GENERAL', '876-928-5111', 'info@odpem.gov.jm',
 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP, 1);

-- Roles (DRIMS)
INSERT INTO role (code, name, description) VALUES
('SYSTEM_ADMINISTRATOR', 'System Administrator', 'Full system access and configuration'),
('LOGISTICS_MANAGER', 'Logistics Manager', 'Oversees all logistics operations'),
('LOGISTICS_OFFICER', 'Logistics Officer', 'Manages inventory and fulfillment'),
('MAIN_HUB_WAREHOUSE', 'Main Hub Warehouse', 'Main warehouse operations'),
('SUB_HUB_WAREHOUSE', 'Sub Hub Warehouse', 'Sub-hub warehouse operations'),
('AGENCY_HUB', 'Agency Hub', 'Agency requests and receipts'),
('INVENTORY_CLERK', 'Inventory Clerk', 'Stock management'),
('AUDITOR', 'Auditor', 'Compliance and audit access');

-- Note: Admin user with password hash should be created via application

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
